### PR TITLE
Make relative paths resolve against executable directory.

### PR DESCRIPTION
**Pull request by aforge**
To make things consistent with how the server treats paths.

### CODE REVIEW

**Comment by or-else** [comment]
I don't remember why I made it to resolve against the exec path. The resolution against the current dir looks more conventional. Maybe do it the other way around?

**Comment by or-else** [comment]
Actually, I do remember now - that made some sense because of the way sandbox was deployed back then. I don't think it matters anymore. Current dir makes more sense.

**Comment by aforge** [comment]
Changed it to use cwd for the config.
I'm keeping it executable path for the templates dir as this comment explains:
https://github.com/tinode/chat/blob/devel/server/main.go#L564-L571

Or do you think we should change it to the cwd as well?

**Review by or-else — APPROVED** [review]

**Comment by or-else** [comment]
I would resolve all paths from the CWD. It's the option of least surprise.

**Pull request merged**
