### PR TITLE
support aws3 s3 for media files (#143)

### PR DESCRIPTION
**Pull request by vardef**

### CODE REVIEW

**Comment by or-else** [comment]
Great, thanks a lot!

If you don't mind, could you please sign the form again: 
https://github.com/tinode/chat/blob/master/docs/CLA.md

I know you signed it already but I need your real name there. Thanks!

**Comment by vardef** [comment]
I signed it!

**Comment by or-else** [comment]
Yes, I see that you have signed it twice, but in the field `Your full name (first and last)` I need your actual personal name, not github handle. Thanks!

**Comment by vardef** [comment]
Check it again

**Comment by or-else** [comment]
Yes! Thanks you!

**Comment by or-else** [comment]
I'll try to include it into the next release.

**Comment by or-else** [comment]
I've substantially rewritten your patch: 
* Removed dependencies on github.com/kataras/iris/core/errors and github.com/google/go-cloud/* because they don't seem to add value when using just the AWS.
* Changed the download mechanism because S3 does not support Seeker interface. Instead of piping the download through the Tinode server, the downloads are now served directly from the s3 bucket.
* General changes for code style and fixes for lint warnings.

I'm going to close this pull request without merging, but the s3 support based on your PR is now in devel branch: https://github.com/tinode/chat/blob/devel/server/media/s3/s3.go

Thanks!

**Pull request closed without merging**
