### PR TITLE
Add new features and bug fixed, also published to nuget [Tinode.ChatBot]

### PR DESCRIPTION
**Pull request by BenDerPan**
ChangeLogs:
1. Add message  event notify, such as ServerPresEvent,ServerMetaEvent,CtrlMessageEvent,ServerDataEvent;
2. Add Subscriber for subscriber list;
3 Fixed no avatar meta data null reference exception;

I published the ChaBot .net library to [nuget.org](https://www.nuget.org/packages/Tinode.ChatBot/)

### CODE REVIEW

**Comment by or-else** [comment]
BTW, what do you think if I move your chatbot to a separate repository and give you commit access to it?

**Comment by or-else** [comment]
Something like https://github.com/tinode/csharpbot. Or you come up with a better name for it.

**Comment by BenDerPan** [comment]
That would be fine, your advised name is fine, but the release lib name will keep Tinode.ChatBot on nuget.

**Comment by or-else** [comment]
Done. Once you accept the invite here https://github.com/tinode/csharpbot/invitations you should have commit access to the https://github.com/tinode/csharpbot

**Pull request merged**
