### PR TITLE
add MariaDB to README.md

### PR DESCRIPTION
**Pull request by robertsilen**
Suggesting to add mention of MariaDB to README as discussed in https://github.com/tinode/chat/issues/923

### CODE REVIEW

**Comment by or-else** [comment]
I would rather not mention it this way because it creates an impression that it's fully supported just like other databases. We do not support it explicitly and do not test on it. Given some differences in the way MySQL and MariaDB store JSON columns it's possible that they will become incompatible in the future. I would rather mention it as 

`MySQL (and MariaDB as long as it's SQL and binary compatible)`

**Comment by robertsilen** [comment]
How about adding CI testing for both MariaDB and MySQL to verify support for both? Can you provide any guidance on CI for your project?

**Comment by or-else** [comment]
It would be great. 
We have no CI consequently no guidance. And automated tests only for MongoDB.

**Comment by or-else** [comment]
Any update on this?

**Pull request closed without merging**
