### PR TITLE
Add MYSQL DSN Environment Variable

### PR DESCRIPTION
**Pull request by TaylorChristie**
Currently, the MySQL database runs as the root user without a password, obviously that isn't the best for a live environment so I modified the docker files slightly to support a user defined DSN.

### CODE REVIEW

**Comment by or-else** [comment]
Thanks!

**Comment by TaylorChristie** [comment]
Could you push this change to the docker hub so I can start using it on the official image?

Thanks!

**Comment by or-else** [comment]
I'm currently travelling thus delayed responses. Will try to do it over the weekend.

**Comment by or-else** [comment]
done

**Pull request merged**
